name: ESLint Checker

on:
  pull_request:
    branches: [ submission ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        working-directory: ./mission
        run: yarn
        
      - name: Run ESLint
        working-directory: ./mission
        run: eslint . --fix-dry-run --ext .js,.jsx,.ts,.tsx